-- Seed data for MySQL 8.0 portfolio backend

-- Admin user (email: admin@example.com, password: admin123 hashed with bcrypt $2a$10$wE9sY6p7A4v... or generated dynamically at runtime if absent)
-- Insert 6 flagship projects
INSERT INTO projects (id, slug, index_label, title, subtitle, summary, highlights, stack, image_url, image_alt, live_url, github_url, status, featured, sort_order)
VALUES
('medconnect-uuid', 'medconnect', '001', 'MedConnect', 'Full-Stack Healthcare Management Platform', 'A healthcare management platform covering appointment booking, patient records, health vitals monitoring and telemedicine workflows.', '["Role-based authentication with separate dashboards for patients, doctors and administrators.", "Appointment management, availability scheduling and patient history access.", "Express.js APIs and MongoDB data management behind a responsive frontend."]', '["React", "Vite", "TypeScript", "Tailwind CSS", "Express.js", "MongoDB"]', '/src/assets/project-medconnect.jpg', 'MedConnect dashboard with appointments, patient vitals and doctor list', 'https://medconnect-8x1l.onrender.com', 'https://github.com/abhijit5996/MedConnect', 'published', TRUE, 1),

('fiteats-uuid', 'fiteats', '002', 'FitEats', 'Food Ordering & Recommendation Platform', 'A full-stack food ordering application featuring a personalized recommendation engine to enhance user engagement.', '["Developed and deployed the full-stack ordering application on Render.", "Personalized recommendation engine integrated into the ordering flow."]', '["React.js", "Node.js", "Express.js", "MongoDB"]', '/src/assets/project-fiteats.jpg', 'FitEats meal ordering interface with nutrition summary', 'https://final-nutriorder.onrender.com', 'https://github.com/abhijit5996/FitEats-Food-Recommendation-and-Delivery-Partner', 'published', TRUE, 2),

('recsys-uuid', 'recommendation-system', '003', 'Intelligent Recommendation System', 'ML-Based Suggestion Engine', 'A machine-learning recommendation engine using content-based filtering to provide tailored user suggestions.', '["Engineered a recommendation engine using content-based filtering techniques."]', '["Python", "Pandas", "NumPy", "Streamlit", "Machine Learning"]', '/src/assets/project-recsys.jpg', 'Streamlit recommendation dashboard with similarity scores', NULL, 'https://github.com/abhijit5996/Python-Project-Recommendation-System', 'published', FALSE, 3),

('pathfinder-uuid', 'pathfinder', '004', 'PathFinder', 'Travelling Salesman Problem Visualization Tool', 'An interactive algorithm visualization tool that computes and maps optimal routes across complex multi-node networks.', '["Interactive visualization of route optimization and TSP concepts."]', '["React.js", "JavaScript", "Algorithm Visualization"]', '/src/assets/project-pathfinder.jpg', 'Route optimization visualizer with nodes and optimal path', NULL, 'https://github.com/abhijit5996/pathfinder-pro', 'published', FALSE, 4),

('transithub-uuid', 'transithub', '005', 'TransitHub', 'Last-Mile Transit Solution', 'A scalable transit platform focused on last-mile transportation.', '["Architected with TypeScript for type-safe components, improving maintainability and reducing runtime errors."]', '["React", "TypeScript", "Tailwind CSS"]', '/src/assets/project-transithub.jpg', 'Transit platform with routes, live map and schedules', NULL, 'https://github.com/abhijit5996/Transit-Hub', 'published', FALSE, 5),

('khet-uuid', 'khet-se-ghar-tak', '006', 'Khet-se-ghar-tak', 'Farm-to-Table E-Commerce Platform', 'A responsive farm-to-consumer e-commerce platform designed to facilitate direct farmer-to-consumer transactions.', '["Engineered to streamline the supply chain between farmers and consumers."]', '["React", "TypeScript", "Tailwind CSS"]', '/src/assets/project-khetseghartak.jpg', 'Farm-to-table e-commerce storefront with produce and farmer profiles', NULL, 'https://github.com/abhijit5996/grocer-roots-link', 'published', FALSE, 6)
ON DUPLICATE KEY UPDATE id=id;
